global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  # - job_name: 'user-service'
  #   scrape_interval: 5s
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: [ 'user-service:9001' ]

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'node_exporter:9100' ]
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'cadvisor:8080' ]
