apiVersion: 1

deleteDatasources:
  - name: Prometheus
  # - name: Tempo
  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      # exemplarTraceIdDestinations:
      #   - name: trace_id
      #     datasourceUid: tempo
  
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: \[.+,(.+?),
          name: traceId
          url: $${__value.raw}

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus


  # - name: Tempo
  #   type: tempo
  #   uid: tempo
  #   url: http://tempo:3200
  #   access: proxy
  #   basicAuth: false
  #   jsonData:
  #     tracesToLogsV2:
  #       # Field with an internal link pointing to a logs data source in Grafana.
  #       # datasourceUid value must match the uid value of the logs data source.
  #       datasourceUid: 'loki'
  #       spanStartTimeShift: '1h'
  #       spanEndTimeShift: '-1h'
  #       tags: ['job', 'instance', 'pod', 'namespace']
  #       filterByTraceID: false
  #       filterBySpanID: false
  #       customQuery: true
  #       query: 'method="${__span.tags.method}"'
  #     tracesToMetrics:
  #       datasourceUid: 'prom'
  #       spanStartTimeShift: '1h'
  #       spanEndTimeShift: '-1h'
  #       tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
  #       queries:
  #         - name: 'Sample query'
  #           query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
  #     serviceMap:
  #       datasourceUid: 'prometheus'
  #     nodeGraph:
  #       enabled: true
  #     search:
  #       hide: false
  #     lokiSearch:
  #       datasourceUid: 'loki'
  #     traceQuery:
  #       timeShiftEnabled: true
  #       spanStartTimeShift: '1h'
  #       spanEndTimeShift: '-1h'
  #     spanBar:
  #       type: 'Tag'
  #       tag: 'http.path'
